spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/todo_app_db
      auto-index-creation: true
#      username:
#      password:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/todoapp/protocol/openid-connect/certs